Enhance RequestHandler, make addTask and deleteTask void
lkorasik/ToDoBot pull request #24
Opened 2020-10-13 17:48 UTC by ddqof

2020-10-13 18:49 UTC, lkorasik requested changes

2020-10-13 18:49 UTC, lkorasik commented on src/main/java/com/core/Core.java
> +    public void deleteTask(String index) throws notExistingTaskIndexException, incorrectTaskIdTypeException {
А можно подробнее, что делает throws тут?

2020-10-13 18:49 UTC, lkorasik commented on src/main/java/com/core/CoreExceptions.java
> +class incorrectTaskIdTypeException extends Exception{
А разве можно объявлять в одном файле два класса?

2020-10-14 03:35 UTC, ddqof commented on src/main/java/com/core/Core.java
> +    public void deleteTask(String index) throws notExistingTaskIndexException, incorrectTaskIdTypeException {
> А можно подробнее, что делает throws тут?

насколько я понял, это указатель на то, что метод может выбрасывать исключения

2020-10-14 03:37 UTC, ddqof commented on src/main/java/com/core/CoreExceptions.java
> +class incorrectTaskIdTypeException extends Exception{
> А разве можно объявлять в одном файле два класса?

Видимо можно. Разнести по разным файлам?

2020-10-14 04:16 UTC, lkorasik commented on src/main/java/com/core/CoreExceptions.java
> +class incorrectTaskIdTypeException extends Exception{
Да

2020-10-14 05:12 UTC, lkorasik approved these changes

2020-10-14 05:13 UTC, merged